# Generated by Django 3.1.4 on 2021-01-05 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='products',
        ),
        migrations.AddField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
            preserve_default=False,
        ),
    ]
